spring.application.name=nota_fiscal

# Configuracao do banco de dados postgres criado e rodando via docker
spring.datasource.url=jdbc:postgresql://localhost:5432/postgre_sonner
spring.datasource.username=postgres
spring.datasource.password=SICSADM

#define qual drive JDBC o Spring vai usar para conectar ao Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# controla como o hibernate vai tratar a estrutura do banco na inicializacao da aplicacao
spring.jpa.hibernate.ddl-auto=update
